### PR TITLE
Manon/july 13

### PR DESCRIPTION
**Pull request by CryptoManion**
Adding articles

### CODE REVIEW

**Comment by yurikoinaba** [comment]
With the Academy, most likely, the errors from Cloudflare Pages are build errors. You can replicate them by running `npm run build` when you don't have access to the Cloudflare logs

cc @Haxen2000 for when providing support

**Review by Haxen2000 — APPROVED** [review]
I have not had a read everything to check for typos, but all seems well.

**Comment by Haxen2000** [comment]
@rabyyuson we need a second ✅ before we can merge 🙀

**Comment by rabyyuson** [comment]
@Haxen2000 @CryptoManion there were issues with the pull request that I had to address first when I started looking at this (that is why the multiple commits):

1. Invalid image path
2. Invalid page reference
3. Incorrect link reference
4. Missing file extensions more specifically `.md`
5. Incorrect heading format
6. Incorrect page title

I addressed all of them and now both pages `/smart-contract-wallets` and `/smart-contract-developers` works correctly which you can view when you view it on https://73081924.horizen-academy-v2.pages.dev.

**Review by rabyyuson — APPROVED** [review]

**Comment by CryptoManion** [comment]
ok thank you @rabyyuson .
I'll see what happens with the new articles because I was sure I had the right link and page references.
Thanks for fixing it

**Comment by rabyyuson** [comment]
@CryptoManion no problem. Please let me know if you need any other assistance with this.

**Review by CryptoManion — COMMENTED** [review]
Ok

**Comment by CryptoManion** [comment]
Ok for merging

**Pull request merged**
